### ISSUE TITLE
It's not working big file.

### ISSUE THREAD

**Issue by alonewolfx2** [Manawyrm/ESP8266-HTTP#1]
It's not working big files.(bigger than 1226 Byte)

**Comment by Manawyrm** [comment]
That could be a heap issue. Are you using httpDL or http.lua? 
When using httpDL, could you put in a print(node.heap()) on line 26?

**Comment by alonewolfx2** [comment]
no it isn't heap issue. i am using httpDL.lua and here is log. i am trying download dht11.lua and file size is 7.5kb
```
> 15560
16696
16824
16824
16696
19432
downloadComplete..
>for k,v in pairs(file.list()) do print(k.."   "..v.." bytes") end
init.lua   29 bytes
example.lua   433 bytes
dht11.lua   1226 bytes
> 
```

**Comment by Manawyrm** [comment]
Interesting. What does it do? Is the file just to small? Or does it crash? 
On what point in the file does it stop? Can you dump the dht11.lua from the chip?

**Comment by alonewolfx2** [comment]
donwloaded file to small for ex: i tried wrote test.lua it have 450 lines and per line has just node.heap().
i tried download and i says finished. i saw 102 lines when i look in esp file system.

**Comment by Manawyrm** [comment]
I'm still not 100% sure what the .flush Command does, as it is not properly documented in the wiki. 

```
		if (payloadFound == true) then
			file.write(payload)
		else
			if (string.find(payload,"\r\n\r\n") ~= nil) then
				file.write(string.sub(payload,string.find(payload,"\r\n\r\n") + 4))
				payloadFound = true
			end
		end

		payload = nil
		collectgarbage()
	end)
	conn:on("disconnection", function(conn) 
		conn = nil
		file.flush()
		file.close()
		callback("ok")

```

Could you try this?

**Comment by alonewolfx2** [comment]
nothing changed

**Comment by Manawyrm** [comment]
Hmm, the current changelog from nodemcu-firmware says something about "fix file.read() api, take 0xFF as a regular byte, not EOF.". 

Could you try again with the recent firmware?

**Comment by Manawyrm** [comment]
btw: There was a really stupid bug in the code that caused this. Thanks for reporting it, it's now fixed :)

**Comment by alonewolfx2** [comment]
Really? Did you update last code on github?

**Comment by Manawyrm** [comment]
axelkoehler sent a pull request: https://github.com/Manawyrm/ESP8266-HTTP/commit/be4909ed3170acb1e294719007b47ac25ae2a7c4

Have a look at it.

**Comment by alonewolfx2** [comment]
Just one wrong line :)
